from sqlalchemy import Column, Integer, String, DateTime
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Polo(Base):
    __tablename__ = "polos"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True, comment="Identificador único da tabela (chave primária)")
    id_unidade_fisica = Column(Integer, unique=True, index=True, nullable=False, comment="ID obrigatório da unidade física, único")
    name = Column(String, nullable=False, comment="Nome do polo (obrigatório)")
    print_name = Column(String, nullable=True, comment="Nome para impressão")
    acronym = Column(String, nullable=True, comment="Sigla do polo")
    street = Column(String, nullable=True, comment="Logradouro (endereço)")
    number = Column(String, nullable=True, comment="Número do endereço")
    neighborhood = Column(String, nullable=True, comment="Bairro")
    postal_code = Column(String, nullable=True, comment="CEP")
    email = Column(String, nullable=True, comment="E-mail")
    cnpj = Column(String, nullable=True, comment="CNPJ da unidade")
    phones = Column(String, nullable=True, comment="Telefones de contato")
    city_id = Column(Integer, nullable=True, comment="ID da cidade")
    state_id = Column(Integer, nullable=True, comment="ID do estado")
    status = Column(String, nullable=True, comment="Status do polo (ativo, inativo, etc)")
    activation_date = Column(DateTime, nullable=True, comment="Data de ativação da unidade")
    inactivation_date = Column(DateTime, nullable=True, comment="Data de inativação da unidade")
    inep_code = Column(Integer, nullable=True, comment="Código INEP")
    city_name = Column(String, nullable=True, comment="Nome da cidade")
    state_acronym = Column(String, nullable=True, comment="Sigla do estado")
    state_name = Column(String, nullable=True, comment="Nome do estado")
    responsible_name = Column(String, nullable=True, comment="Nome do responsável")
    responsible_phone = Column(String, nullable=True, comment="Telefone do responsável")
    responsible_cellphone = Column(String, nullable=True, comment="Celular do responsável")
    responsible_email = Column(String, nullable=True, comment="E-mail do responsável")
    responsible_profile_id = Column(Integer, nullable=True, comment="ID do perfil do responsável")
    supervisor_name = Column(String, nullable=True, comment="Nome do supervisor")
    supervisor_profile_id = Column(Integer, nullable=True, comment="ID do perfil do supervisor")
    hide_in_form = Column(Integer, nullable=True, comment="Indica se não apresenta no formulário de atendimento (0 ou 1)")
    complement = Column(String, nullable=True, comment="Complemento do endereço")
    unit_type = Column(String, nullable=True, comment="Tipo da unidade")
    attendance_hours_note = Column(String, nullable=True, comment="Observação sobre horário de atendimento")